#  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
numerosFibbonaci = []
a = 1
b = 2
numerosFibbonaci.append(a)
numerosFibbonaci.append(b)
while b < 4000000:  # While values do not exceed four million
  tmp = b
  b = b + a
  a = tmp
  numerosFibbonaci.append(b)


result = 0
for i in numerosFibbonaci:
    if i % 2 == 0:
        result += i

print(result)
